version: '3'
services:
  slurm:
    build: .
    command: tail -f /dev/null
    volumes:
      - /mnt/test:/mnt/test
      - ./src/:/usr/src/
    working_dir: /usr/src
    command: npm start
    ports:
      - "5000:5000"
